# Generated by Django 3.2.3 on 2021-06-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='published'),
        ),
    ]
