# Generated by Django 3.2.3 on 2021-06-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='published'),
        ),
    ]
