# Generated by Django 3.2.3 on 2021-06-20 03:40

from django.db import migrations, models
import review.models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20210617_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='reviews/default.jpg', upload_to=review.models.upload_to, verbose_name='Image'),
        ),
    ]
