# Generated by Django 3.2.3 on 2021-06-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210620_0105'),
        ('review', '0011_alter_review_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category',
        ),
        migrations.AddField(
            model_name='review',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
