# Generated by Django 3.2.3 on 2021-06-20 03:40

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=220)),
                ('studio', models.CharField(default='', max_length=220)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, default='reviews/default.jpg', upload_to=game.models.upload_to, verbose_name='Image')),
                ('rating', models.DecimalField(decimal_places=2, editable=False, max_digits=3)),
            ],
        ),
    ]
