# Generated by Django 3.2.3 on 2021-06-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=3),
        ),
    ]
