# Generated by Django 3.2.3 on 2021-06-20 04:16

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, default='games/default.jpg', upload_to=game.models.upload_to, verbose_name='Image'),
        ),
    ]
