# Generated by Django 3.2.3 on 2021-06-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='rating',
            new_name='gold_average',
        ),
        migrations.AddField(
            model_name='game',
            name='no_gold_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique_for_date='published'),
        ),
    ]
