# Generated by Django 3.2.3 on 2021-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210620_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gold_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='silver_average',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True),
        ),
    ]
